## https://github.com/WallaceWilliam

---
- name: fail2ban restart  
  service:
    name: fail2ban
    state: restarted

- name: zabbix-agent restart
  service:
    name: zabbix-agent
    state: restarted
