# meta file for cron-apt
---
galaxy_info:
  role_name: cron-apt
  author: WallaceWilliam
  description: Set up cron-apt in Debian-like systems
  license: MIT
  min_ansible_version: 2.9.0.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - system
    - packaging
dependencies: []

