# meta file for 
---
galaxy_info:
  role_name: logon_notify_mail
  author: WallaceWilliam
  description: email information on logon
  license: MIT
  min_ansible_version: 2.9.0.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - system
    - packaging
dependencies: []

